swagger: '2.0'
info:
  version: "1"
  title: Harald
  description: The one notification
consumes:
  - application/json
produces:
  - application/json
basePath: /api/v1/
paths:
  /messages:
    post:
      summary: Queue a message for dispatching
      parameters:
        - in: body
          name: message
          required: true
          schema:
            $ref: "#/definitions/message"
      responses:
        202:
          description: Accepted - message is queued for dispatching.
        400:
          description: Bad request - required input is missing.
        422:
          description: Unprocessable entity - capability ID can't be processed.
        503:
          description: Service unavailable - error trying to send the message.
  /connections:
    get:
      summary: A queryable collection of connections between publishers and communication channels
      parameters:
      - in: query
        name: publisherType
        type: string
        enum: [capability]
        required: false
      - in: query
        name: publisherId 
        type: string
        required: false
      - in: query
        name: channelType
        type: string
        enum: [slack]
        required: false
      - in: query
        name: channelId
        type: string
        required: false
      responses:
        200:
          description: Returns a collection of channels
          schema:
            $ref: "#/definitions/connections"
  /channels:
    get:
      summary: A queryable collection of existing communication channels
      parameters:
        - in: query
          name: type
          type: string
          enum: [slack]
          required: false
      responses:
        200:
          description: Returns a collection of channels
          schema:
            $ref: "#/definitions/channels"
definitions:
  message:
    type: object
    properties:
      capabilityId:
        type: string
      message:
        type: string
  channel:
    type: object
    properties:
      type:
        type: string
        enum: [slack]
      name:
        type: string
      id:
        type: string
  channels:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/channel"
  connection:
    type: object
    properties:
      publisherType:
        type: string
        enum: [slack]
      publisherName:
        type: string
      publisherId:
        type: string
      channelType:
        type: string
        enum: [slack]
      channelName:
        type: string
      channelId:
        type: string
  connections:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: "#/definitions/connection"