openapi: 3.0.0
info:
  version: "1"
  title: Harald
  description: The one notification
paths:
  /messages:
    post:
      summary: Queue a message for dispatching
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/message"
        required: true
      responses:
        "202":
          description: Accepted - message is queued for dispatching.
        "400":
          description: Bad request - required input is missing.
        "422":
          description: Unprocessable entity - capability ID can't be processed.
        "503":
          description: Service unavailable - error trying to send the message.
  /connections:
    get:
      summary: A queryable collection of connections between publishers and
        communication channels
      parameters:
        - in: query
          name: senderType
          required: false
          schema:
            type: string
            enum:
              - capability
        - in: query
          name: senderId
          required: false
          schema:
            type: string
        - in: query
          name: channelType
          required: false
          schema:
            type: string
            enum:
              - slack
        - in: query
          name: channelId
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Returns a collection of channels
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/connections"
  /channels:
    get:
      summary: A queryable collection of existing communication channels
      parameters:
        - in: query
          name: type
          required: false
          schema:
            type: string
            enum:
              - slack
      responses:
        "200":
          description: Returns a collection of channels
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/channels"
servers:
  - url: /api/v1/
components:
  schemas:
    message:
      type: object
      properties:
        capabilityId:
          type: string
        message:
          type: string
    channel:
      type: object
      properties:
        type:
          type: string
          enum:
            - slack
        name:
          type: string
        id:
          type: string
    channels:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/channel"
    connection:
      type: object
      properties:
        senderType:
          type: string
          enum:
            - capability
        senderName:
          type: string
        senderId:
          type: string
        channelType:
          type: string
          enum:
            - slack
        channelName:
          type: string
        channelId:
          type: string
    connections:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/connection"
