apiVersion: apps/v1
kind: Deployment
metadata:
  name: harald
  namespace: $(kubernetes-namespace)
  labels:
    project: selfservice
    department: devex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harald
  template:
    metadata:
      labels:
        app: harald
        project: selfservice
        department: devex
    spec:
      initContainers:
      - name: dbmigrations
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/harald/dbmigrations:$(Build.BuildId)
        env:
        - name:  PGDATABASE
          value: haralddb
        - name:  PGHOST
          value: $(PGHOST)
        - name:  PGPORT
          value: "1433"
        - name:  PGUSER
          value: $(PGUSER)
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: harald
              key: password
      containers:
      - name: harald
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/ded/harald:$(Build.BuildId)
        ports:
        - containerPort: 80
          name: web
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: HARALD_DATABASE_CONNECTIONSTRING
          valueFrom:
            secretKeyRef:
              name: harald
              key: connection-string
        - name: SLACK_API_BASE_URL
          value: https://slack.com
        - name: SLACK_API_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: harald
              key: slack-auth-token
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          httpGet:
            port: web
            path: /healthz
          
