apiVersion: v1
kind: Service
metadata:
  name: harald
  namespace: $(kubernetes-namespace)
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: harald
    project: selfservice
    department: devex    
    component: harald
spec:
  ports:
  - name: external
    port: 80
    targetPort: web
  selector:
    app: harald